---
# argument spec file for katerina2121.docker.docker-installation

argument_specs:
  main:
    short_description: Installs Docker on Ubuntu and manages docker group membership.
    options:
      docker_installation_users:
        type: list
        elements: str
        description: List of system users to be added to the `docker` group for non-root access to the Docker daemon.
        default: ["{{ ansible_user }}"]
