---

- name: Include tasks for Ubuntu or Debian systems
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution in ['Ubuntu', 'Debian']

- name: Ensure group docker exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker-installation-users }}"
  notify: reset ssh session